### ISSUE TITLE
Mentionname vs. username vs. german umlauts

### ISSUE THREAD

**Issue by anx-ag** [ergon/migratemost#17]
On hipchat, we had one user with e-mail address jmueller@domain.com and we used e-mail as the login field. The nicknames could be chosen by everyone on their own, so people got creative and one f.ex. also used umlauts in the mentionname (in this case, @jmüller). After the migration, in Mattermost the username is now "jmuller".

Is that because of an limitation of mattermost or will this cause any issues now? I can see that mentions do not seem to show up for this user, but I'm now sure and am still grasping through the history.

**Comment by 7-plus-t** [comment]
Migratemost does not edit the username, so I assume the cause is this:
https://github.com/mattermost/mattermost-server/issues/1528

You could verify this, by importing a user with umlaut in the username using the bulk importer and see if Mattermost imports it without it.

If this is the case, then in order for the mentions to match, you or Migratemost would have to rewrite the chat history fixing all mentions with the non UTF-8 username.
